# Generated by Django 4.1.7 on 2023-06-22 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='ordercustomer',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='upload_product',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL),
        ),
    ]
