# Generated by Django 4.1.7 on 2023-06-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_customorder_ordercustomer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='prime_pk',
            field=models.IntegerField(default=0),
        ),
    ]
