# Generated by Django 4.1.7 on 2023-07-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_customorder_prime_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='orderconform',
            field=models.BooleanField(default=False),
        ),
    ]
