# Generated by Django 4.1.7 on 2023-06-19 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_many', models.IntegerField()),
                ('total', models.IntegerField()),
                ('dateandtime', models.DateTimeField()),
                ('product_request', models.BooleanField(default=False)),
                ('product_accepted', models.BooleanField(default=False)),
                ('riched', models.BooleanField(default=False)),
                ('taken', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.upload_product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='username',
        ),
        migrations.DeleteModel(
            name='delivery',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
