# Generated by Django 4.1.7 on 2023-06-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderes_remove_orders_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderes',
            name='dateandtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
