# Generated by Django 4.1.7 on 2023-06-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_orderes_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderes',
            name='rating',
        ),
        migrations.AddField(
            model_name='orderes',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
